### PR TITLE
Use of LevelDB_jll, documentation and github workflows 

### PR DESCRIPTION
**Pull request by sadit**
This pull request contains integration with GH actions, documentation and LevelDB_jll (BinaryBuilder) as a way to make broader and simpler to mantain

### CODE REVIEW

**Comment by sadit** [comment]
Dear @jerryzhenleicai 

In addition to the previous changes, I also added support for other kinds of key-value types and iterators. These features changed the API and broke compatibility, so they increased the version number.

Please consider this pull request proposal.

Best,
Eric

**Comment by asbisen** [comment]
Can we please get this PR merged?

**Comment by jerryzhenleicai** [comment]
Sorry for the proscratination , I will try to review in the next few days.

**Comment by jerryzhenleicai** [comment]
What does the Github Actions do? I am a bit unsure we want to introduce GitHub proprietary logic into this source package.

**Comment by sadit** [comment]
Hi, GitHub Actions automatizes tests in this package. The idea is that after any push or pull request, a GHA container is run and verifies that tests are still passing. Such that the contribution, owner, and other people know if the commit is working, at least under the recorded tests

**Comment by asbisen** [comment]
Hi Jerry, Can we please merge this PR if there are no objections?

**Comment by sadit** [comment]
I am happy with my private fork, but LevelDB is quite helpful and can positively impact people looking to create systems with the Julia language, mostly where LMDB is not the best option.

We can fork this repo + the commit and re-register the package under another name - something like LevelDB2. We can also think of joining it to some organization to simplify its maintaining

**Pull request closed without merging**
